name: Redstone duplication bug.
description: There is a way to duplicate redstone using available craft and gringers from tech mods.
labels: [ "bug" ]
body:
    -   type: textarea
        attributes:
            label: Describe the Bug.
            description: There is a way to duplicate redstone using available craft and gringers from tech mod.
            value: | There is a way to duplicate redstone using available craft and gringers from tech mods.
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Reproduction Steps
            description: Tell us about the steps to reproduce the bug
            value: |
                1. Craft "Raw Redstone Block" using 4 "Redstone".
                2. Put "Raw Redstone Block" in "Grinder" and get 8 "redstone" or do the same with but with "Industrial grinder" or "Macerator"
                3. Repeat process with output from step 2 to get endless source of "redstone"
                ...
        validations:
            required: false
    -   type: textarea
        attributes:
            label: Screenshots and Videos
            description: If applicable, add screenshots or videos to help explain your problem
        validations:
            required: false
    -   type: input
        attributes:
            label: Crash Report or Log
            description: If applicable, please add a **link** to the crash report or log that was created when this issue occured. You can upload the crash report to a site like Pastebin or GitHub Gist. Please **do not** paste the whole crash report in this issue
        validations:
            required: false
    -   type: input
        attributes:
            label: Operating System
            description: The operating system you were using when the bug occured
            placeholder: Windows 11
        validations:
            required: true
    -   type: dropdown
        attributes:
            label: Minecraft Version
            description: The version of Minecraft you were using when the bug occured
            options:
                - "Prominence I 1.19.2"
                - "Prominence II 1.20.1"
        validations:
            required: true
    -   type: dropdown
        attributes:
            label: Modloader
            description: The version of Minecraft you were using when the bug occured
            options:
                - "Forge"
                - "Fabric"
        validations:
            required: true
    -   type: input
        attributes:
            label: Modpack Version
            description: The Modpack version you where using example bmc v52
        validations:
            required: true
    -   type: dropdown
        attributes:
            label: Optifine
            description: Did you used Optifine in our packs?
            options:
                - "I used Optifine"
                - "No"
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Other Mods
            description: Any other mods you added to our packs? if yes please list any other mods.
        validations:
            required: false
    -   type: markdown
        attributes:
            value: "Thank you for taking the time to make this bug report and to help improve Better Minecraft"
